[package]
name = "function_host"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
common = { workspace = true }
database = { workspace = true }
funrun_proto = { workspace = true }
indexing = { workspace = true }
parking_lot = { workspace = true }
pb = { workspace = true }
pb_funrun = { workspace = true }
tonic = { workspace = true }
udf = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
errors = { workspace = true }
keybroker = { workspace = true }
model = { workspace = true }
serde_json = { workspace = true }
sync_types = { workspace = true }
tokio = { workspace = true }
usage_tracking = { workspace = true }
value = { workspace = true }
vector = { workspace = true }

[lints]
workspace = true
